/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NameRideRouteImport } from './routes/name-ride'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleVehicleIdRouteImport } from './routes/vehicle.$vehicleId'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NameRideRoute = NameRideRouteImport.update({
  id: '/name-ride',
  path: '/name-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleVehicleIdRoute = VehicleVehicleIdRouteImport.update({
  id: '/vehicle/$vehicleId',
  path: '/vehicle/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/feed': typeof FeedRoute
  '/name-ride': typeof NameRideRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/tracking': typeof TrackingRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/feed': typeof FeedRoute
  '/name-ride': typeof NameRideRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/tracking': typeof TrackingRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit-profile': typeof EditProfileRoute
  '/feed': typeof FeedRoute
  '/name-ride': typeof NameRideRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/summary': typeof SummaryRoute
  '/tracking': typeof TrackingRoute
  '/vehicle/$vehicleId': typeof VehicleVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit-profile'
    | '/feed'
    | '/name-ride'
    | '/profile'
    | '/settings'
    | '/share'
    | '/summary'
    | '/tracking'
    | '/vehicle/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit-profile'
    | '/feed'
    | '/name-ride'
    | '/profile'
    | '/settings'
    | '/share'
    | '/summary'
    | '/tracking'
    | '/vehicle/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/edit-profile'
    | '/feed'
    | '/name-ride'
    | '/profile'
    | '/settings'
    | '/share'
    | '/summary'
    | '/tracking'
    | '/vehicle/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditProfileRoute: typeof EditProfileRoute
  FeedRoute: typeof FeedRoute
  NameRideRoute: typeof NameRideRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SummaryRoute: typeof SummaryRoute
  TrackingRoute: typeof TrackingRoute
  VehicleVehicleIdRoute: typeof VehicleVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-ride': {
      id: '/name-ride'
      path: '/name-ride'
      fullPath: '/name-ride'
      preLoaderRoute: typeof NameRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle/$vehicleId': {
      id: '/vehicle/$vehicleId'
      path: '/vehicle/$vehicleId'
      fullPath: '/vehicle/$vehicleId'
      preLoaderRoute: typeof VehicleVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditProfileRoute: EditProfileRoute,
  FeedRoute: FeedRoute,
  NameRideRoute: NameRideRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SummaryRoute: SummaryRoute,
  TrackingRoute: TrackingRoute,
  VehicleVehicleIdRoute: VehicleVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
